# Базовый образ Alpine
FROM alpine:latest

# Аргументы для создания пользователя (по умолчанию "dev")
ARG UID=1000
ARG GID=1000
ARG UNAME=dev
ARG GNAME=dev

# Установка переменных окружения для mise
ENV MISE_ROOT=/usr/local/bin/mise
ENV PATH="${MISE_ROOT}/bin:$PATH"

# Установка основных зависимостей и утилит для Alpine
RUN apk update && apk add --no-cache build-base openssl-dev pkgconf git zsh curl wget unzip sudo stow bash shadow fontconfig ttf-inconsolata fzf ripgrep fd tar gzip python3 nodejs npm && rm -rf /var/cache/apk/*

# Создание группы и пользователя с использованием синтаксиса Alpine
RUN addgroup -g ${GID} ${GNAME} && adduser -u ${UID} -g ${GID} -D -s /bin/zsh -G ${GNAME} ${UNAME}

# Настройка sudo для пользователя без пароля
RUN echo "${UNAME} ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/${UNAME} && chmod 0440 /etc/sudoers.d/${UNAME}

# Переключаемся на пользователя root для установки общесистемных инструментов (mise, starship)
USER root

# Установка Neovim
RUN OS=$(uname -s | tr '[:upper:]' '[:lower:]') && ARCH=$(uname -m | sed 's/aarch64/arm64/') && curl -Lo nvim.tar.gz https://github.com/neovim/neovim/releases/download/stable/nvim-$OS-$ARCH.tar.gz && tar -xzf nvim.tar.gz -C /usr/local --strip-components=1 && rm -f nvim.tar.gz

# Установка lazygit
RUN LG_VERSION="0.61.0" && OS=$(uname -s | tr '[:upper:]' '[:lower:]') && ARCH=$(uname -m | sed 's/aarch64/arm64/') && curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/download/v$LG_VERSION/lazygit_${LG_VERSION}_${OS}_${ARCH}.tar.gz" && tar xf lazygit.tar.gz lazygit && install lazygit /usr/local/bin && rm -rf lazygit lazygit.tar.gz

# Установка mise (ex-rtx)
RUN curl https://mise.run | MISE_INSTALL_PATH=/usr/local/bin/mise sh

# Установка starship
RUN curl -sS https://starship.rs/install.sh | sh -s -- --yes

# Переключаемся на пользователя dev
USER ${UNAME}
WORKDIR /home/${UNAME}

# Настройка shell
RUN mkdir -p /home/${UNAME}/.config
COPY --chown=${UNAME}:${GNAME} docker/starship.toml /home/${UNAME}/.config/starship.toml

RUN echo '# Mise and Starship configuration' >> /home/${UNAME}/.zshrc
RUN echo 'eval "$(mise activate zsh)"' >> /home/${UNAME}/.zshrc
RUN echo 'eval "$(starship init zsh)"' >> /home/${UNAME}/.zshrc

# Копирование .tool-versions и установка инструментов через mise
COPY --chown=${UNAME}:${GNAME} .tool-versions /home/${UNAME}/.tool-versions
RUN mise install

# Указываем, что будем использовать zsh по умолчанию
CMD ["/bin/zsh"]
